import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "Electron with nextjs 14",
    description: "Generated by create next app",
};

declare global {
    interface Window {
        electron: {
            getOs: () => void;
            print: () => void;
            on: (channel: string, func: (...args: any[]) => void) => void;
        }
    }
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
